[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.build]
cmds = [
  "cd backend && python -m venv venv",
  "cd backend && source venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && source venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
